// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMessageIndicatorChange();
void onTempChange();
void onThresholdValueChange();

String messageIndicator;
float temp;
float thresholdValue;

void initProperties(){

  ArduinoCloud.addProperty(messageIndicator, READWRITE, ON_CHANGE, onMessageIndicatorChange);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
  ArduinoCloud.addProperty(thresholdValue, READWRITE, ON_CHANGE, onThresholdValueChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
