/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/10d3a683-76c4-46fc-9c45-bd4dfa123a3d

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String messageIndicator;
  float temp;
  float thresholdValue;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include <OneWire.h>
#include <DallasTemperature.h>
#include "thingProperties.h"

#define ONE_WIRE_BUS 4

OneWire oneWire(ONE_WIRE_BUS);

DallasTemperature sensors(&oneWire);

int hotLedPin = 6;
int goneColdLedPin = 8;

void setup() {

  Serial.begin(9600);

  delay(1500);

  sensors.begin();
  pinMode(hotLedPin, OUTPUT);
  pinMode(goneColdLedPin, OUTPUT);

  initProperties();


  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();

  sensors.requestTemperatures();

  temp = sensors.getTempCByIndex(0);

  Serial.println(sensors.getDeviceCount());

  // Test purposes on serial monitor
  Serial.print("Celsius temperature: ");
  Serial.println(temp);

  Serial.print('\n');


  //LED Threshold Code
  if (temp >= thresholdValue) {
    digitalWrite(hotLedPin, HIGH);
    digitalWrite(goneColdLedPin, LOW);
    messageIndicator = "Your beverage is at an optimum temperature!"
                       Serial.print(messageIndicator);
    Serial.println(temp);
  }

  else {
    digitalWrite(goneColdLedPin, HIGH);
    digitalWrite(hotLedPin, LOW);
    messageIndicator = "Your beverage is getting cold! Heat it up!!";
    Serial.print(messageIndicator);
    Serial.println(temp);
  }


  // Delay
  delay(1000);

}

void onThresholdValueChange()  {

}

void onTempChange()  {

}


void onMessageIndicatorChange()  {

}